// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    cold_weather_velocity_trend: {
        name: "cold_weather_velocity_trend";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          schema: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType TIMESTAMP */
          week: string;
          /** @sqlType STRING */
          climate_zone: string;
          /** @sqlType BIGINT */
          units_sold: number;
        }>;
      };
    position_mix_by_zone: {
        name: "position_mix_by_zone";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          schema: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          climate_zone: string;
          /** @sqlType STRING */
          position_status: string;
          /** @sqlType BIGINT */
          position_count: number;
        }>;
      };
    worst_shortfalls: {
        name: "worst_shortfalls";
        parameters: {
          /** STRING - use sql.string() */
          catalog: SQLStringMarker;
          /** STRING - use sql.string() */
          schema: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          store_name: string;
          /** @sqlType STRING */
          city: string;
          /** @sqlType STRING */
          product_name: string;
          /** @sqlType BIGINT */
          on_hand: number;
          /** @sqlType DOUBLE */
          avg_daily_velocity: number;
          /** @sqlType DOUBLE */
          lost_sales_exposure_usd: number;
        }>;
      };
  }
}
